language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  -
  - JPHP_TEST_COMPILED=1
  - JPHP_TEST_CONCURRENT=1

before_install:
 - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
 - unzip -qq apache-maven-3.3.9.zip
 - export M2_HOME=$PWD/apache-maven-3.3.9
 - export PATH=$M2_HOME/bin:$PATH
 - cat /etc/hosts # optionally check the content *before*
 - sudo hostname "$(hostname | cut -c1-63)"
 - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
 - cat /etc/hosts # optionally check the content *after*
 - gradle wrapper
 - chmod +x gradlew

notifications:
 email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: ./gradlew check --stacktrace -Dfile.encoding=UTF-8

addons:
  hosts:
    - myshorthost
  hostname: myshorthost
